# Generated by Django 2.2.6 on 2019-10-09 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.DecimalField(decimal_places=1, max_digits=3)),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('climate', models.CharField(max_length=100)),
                ('fahrenheit', models.BooleanField(default=True)),
            ],
        ),
    ]
