# Generated by Django 2.2.6 on 2020-01-14 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weatherHome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('userEmail', models.CharField(max_length=50)),
                ('passwordHashed', models.CharField(max_length=64)),
                ('passwordSalt', models.CharField(max_length=50)),
                ('dateAccoutCreated', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='date',
            new_name='dateOfWeather',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='climate',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='fahrenheit',
        ),
        migrations.AddField(
            model_name='weather',
            name='rain',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='weather',
            name='temperature',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='weather',
            name='temperatureFeel',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='weather',
            name='weatherStation',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='wind',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.CreateModel(
            name='weatherForUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weatherHome.user')),
                ('weatherStation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weatherHome.weather')),
            ],
        ),
    ]
