# Generated by Django 2.2.6 on 2020-02-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherHome', '0002_auto_20200113_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weather',
            name='weatherStation',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
