# Generated by Django 2.2.6 on 2020-02-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherHome', '0003_auto_20200215_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userFirstName',
            field=models.CharField(default='hellofirstname', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='userLastName',
            field=models.CharField(default='hellolastname', max_length=30),
            preserve_default=False,
        ),
    ]
