# Generated by Django 2.2.6 on 2020-02-23 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherHome', '0005_auto_20200223_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateAccoutCreated',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 14, 39, 52, 513616)),
        ),
    ]
