# Generated by Django 2.2.6 on 2020-02-23 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherHome', '0006_auto_20200223_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dateAccoutCreated',
        ),
        migrations.AddField(
            model_name='user',
            name='dateAccountCreated',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 14, 45, 9, 388564)),
        ),
    ]
