# Generated by Django 2.2.6 on 2020-02-23 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherHome', '0009_auto_20200223_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateAccountCreated',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 14, 49, 10, 80023)),
        ),
        migrations.AlterField(
            model_name='user',
            name='passwordHashed',
            field=models.CharField(max_length=256),
        ),
    ]
