# Generated by Django 2.2.6 on 2020-02-23 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherHome', '0010_auto_20200223_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateAccountCreated',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 14, 50, 19, 857779)),
        ),
        migrations.AlterField(
            model_name='user',
            name='passwordHashed',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='passwordSalt',
            field=models.CharField(max_length=256),
        ),
    ]
