# Generated by Django 2.2.6 on 2020-02-23 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherHome', '0011_auto_20200223_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateAccountCreated',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 14, 51, 51, 383317)),
        ),
        migrations.AlterField(
            model_name='user',
            name='passwordHashed',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='user',
            name='passwordSalt',
            field=models.CharField(max_length=1024),
        ),
    ]
