# Generated by Django 2.2.6 on 2020-02-28 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherHome', '0014_auto_20200226_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='countryAndCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryName', models.CharField(max_length=100)),
                ('twoCharCountryCode', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='dateAccountCreated',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 27, 20, 25, 55, 972543)),
        ),
    ]
