# Generated by Django 2.2.6 on 2020-02-28 02:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherHome', '0015_auto_20200227_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateAccountCreated',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 27, 20, 41, 5, 635221)),
        ),
    ]
